### ISSUE TITLE
Suggestion: Config interface, borderless pop-out windows.

### ISSUE THREAD

**Issue by jbliesener** [waynepiekarski/XTextureExtractor#1] opened 2018-02-19 01:06 UTC
Wow, this is truly an amazing plugin and, I believe, a potential game changer for cockpit builders.

I would suggest a set of configuration files that permit configuring screen positions in the virtual cockpits from text files, maybe, one per aircraft. Would permit user-defined inclusion of other cockpit parts, like standby attitude indicator and such.

I have adopted a similar approach in my plugin that interfaces CPFlight MCPs to X-Plane (https://gitlab.bliesener.com/CPFlight) and it has proven to be feasible. Maybe, we can exchange some ideas about that.

Another important enhancement would be *borderless* pop-out windows with positions and sizes that can be persisted across X-Plane sessions. You imagine what this would be good for? Correct, external PFDs, MFDs and EICASses.

I have experienced some crashes, but at this point I can't yet trace a 100% route to these crashes. I'll let you know when I find out more.

**Comment by waynepiekarski** [comment] 2018-02-20 21:35
I just did an 0.3 release yesterday which now includes configuration files that you can customize to add or remove windows. There is also preliminary Android client support.

Borderless windows are a bit trickier. You can create them, but then they are not movable. So I could add a flag to the text file where you could mark them as borderless, but you could never change them except by editing the file. Would that work?

**Comment by jbliesener** [comment] 2018-02-20 23:45
Great news about the config files. 

About borderless windows: Not sure, but don't you get mouse down/up/drag events on these windows that you could use to reposition them? If that was the case, you could also (manually) detect and handle edge and corner clicks for resize. Or enable the border if you move the mouse over the window or click on it. But obviously all that would work only if you received those mouse events. Since I don't have too much experience with borderless windows, I'm clueless here.

Another question: Do you have any idea about how the plugin impacts on frame rate? I understand that it's basically just a texture blit, which should be handled entirely by the GPU and cause virtually zero processing overhead, but I'm not sure about that. Can you give me a clue?

Keep up the great work!

**Comment by waynepiekarski** [comment] 2018-02-21 00:35
Implementing the move and resize events manually is definitely possible, it is all provided, its just that I don't know much about the XP SDK, and its probably quite messy to implement all this myself. It might be best to have a hotkey that disables the window decorations, so you can still use them to position everything.

The plugin seems to have no impact on frame rate if the windows appear on the same display that X-Plane is already rendering to. If you pop up a window on an empty Windows screen with nothing else, then I saw the FPS on my 4 screen set up drop from 20 to 17 fps. This penalty is the same if you open up the instructor console on that extra monitor, or empty with 2D instruments.

The new Android client also seems to be pretty low impact. I only grab textures for transmission when the last one has been sent, and so it doesn't grab every frame. I also do compression+transmission on a separate thread to avoid stalling X-Plane's render thread.

**Comment by jbliesener** [comment] 2018-02-21 13:13
Great to hear, Wayne. I'll work out a network client in pure Java and/or Python. Might take some weeks, as I'm pretty busy now. I'll let you know about the outcome.

**Comment by jbliesener** [comment] 2018-02-21 13:15
Will the header structure remain stable for version XTEv1 and will future versions be downward compatible?

**Comment by waynepiekarski** [comment] 2018-02-21 20:10
I'm working on a slight change to the protocol XTEv2 which will break compatibility with XTEv1, I'm going to change the port number as well to ensure no one gets these mixed up.

Instead of compressing the whole 2048x2048 texture, now it will only send the specified windows, so it will be a lot more efficient. I will be finishing this tonight. Clients for other platforms will definitely be appreciated.

**Comment by sum1els** [comment] 2018-02-21 20:56
great stuff, thanks Wayne ... I also think Jorg is going to write a cross platform client which will be awesome. i want to as I find these things interesting, but still a little above my head.

**Comment by roarkr** [comment] 2018-02-22 16:42
It would be awesome if this also could be done on the P3D/FSX platform for the PMDG aircrafts. Today you can have pop up windows of all displays and move them around to other monitors on the same PC, but not over the network. PMDG aircrafts are the most used airliners on the P3D/FSX platform and this solution would make you a hero. But, read the EULA carefully before doing it.

**Comment by waynepiekarski** [comment] 2018-02-22 19:17
@jbliesener I just did a push last night with the new XTEv2 plugin and client. This works really well and I don't envisage changing the protocol any more.

**Comment by waynepiekarski** [comment] 2018-02-22 19:20
@roarkr I don't have P3D and don't know anything about it, the last time I worked with anything related was Microsoft Flight Sim 4 from 1989 where I built this ... http://www.tinmith.net/wayne/blog/2017/06/immersive-flight-sim-4.htm :)

XTE uses a lot of undocumented behavior to do what it does, it might be impossible within P3D's architecture. The concept is pretty simple, it just requires someone with deep knowledge of their SDK to build it.

**Comment by waynepiekarski** [comment] 2018-02-22 19:23
@jbliesener @sam1els getting a few more clients written would be awesome though ... having a Java or Qt client that runs on RPi3 and old laptops would be useful to some people, I've seen a few requests for this but don't have time right now to build one myself.

**Comment by waynepiekarski** [comment] 2018-02-23 07:31
Ok, so I did some looking in to this and it wasn't hard to convert the existing code into something for Java. So I will be pushing a new commit that contains this in the java-client directory. It supports clicking on the window to change between displays, and full screen mode. It would work really well on a small Raspberry Pi 3 driving a small display as well.

**Comment by sum1els** [comment] 2018-02-23 14:18
Thanks Wayne ... I tired it, but seems to get the following error, any ideas :

Macbook:java-client$ ./run-xte.sh 192.168.1.27
Leaving argument 192.168.1.27
Connecting to 192.168.1.27 port 52500
Connection established
Waiting for header
Received raw header [XTEv2 Feb 22 2018 23:57:05
ZB738
2048 2048
ND 524 1550 1018 2038
HSI 9 1538 516 2043
EICAS 1040 1550 1527 2028
EICAS-2 1533 1551 2038 2037
CDU 10 544 540 1023
__EOF__
] before PNG stream
Plugin version [XTEv2], aircraft [ZB738], texture 2048x2048
Window [ND] = (524,1550)->(1018,2038)
Window [HSI] = (9,1538)->(516,2043)
Window [EICAS] = (1040,1550)->(1527,2028)
Window [EICAS-2] = (1533,1551)->(2038,2037)
Window [CDU] = (10,544)->(540,1023)
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Width (0) and height (0) must be non-zero
	at java.awt.image.ReplicateScaleFilter.<init>(ReplicateScaleFilter.java:102)
	at java.awt.image.AreaAveragingScaleFilter.<init>(AreaAveragingScaleFilter.java:77)
	at java.awt.Image.getScaledInstance(Image.java:172)
	at net.waynepiekarski.XTextureExtractor.networkLoop(XTextureExtractor.java:168)
	at net.waynepiekarski.XTextureExtractor$2.run(XTextureExtractor.java:58)
	at java.lang.Thread.run(Thread.java:748)

**Comment by waynepiekarski** [comment] 2018-02-23 18:46
I get similar problems on Windows with --fullscreen, but my Mac works fine. What is your java -version and javac -version?

**Comment by sum1els** [comment] 2018-02-23 18:49
Andres-Macbook:extplane andre$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Andres-Macbook:extplane andre$ javac -version
javac 1.8.0_162
Andres-Macbook:extplane andre$

**Comment by waynepiekarski** [comment] 2018-02-23 18:58
Actually I just realized I didn't test on my Mac. I need to look at this later on. There seems to be differences between platforms and I must have a bug.

**Comment by sum1els** [comment] 2018-02-23 19:02
Thanks Wayne !!

**Comment by sum1els** [comment] 2018-02-23 21:09
Wayne .. got it to work on the Mac just by manually specifying a width/height, although it doesn't scale. On windows, it works without manually setting it.

However, I do get the following after a while:

Image header invalid ![33d/!] _[82d/R] _[0d/]
Network loop failed

**Comment by waynepiekarski** [comment] 2018-02-24 03:46
I have pushed a new version which hopefully fixes everything. For some reason, the Java PNG decoder doesn't eat up all the bytes, so I put in some code to properly sync up to the next image header. It should be super reliable now.

Also, I was not resizing the window properly, now I think I'm doing this properly. However, I was never able to reproduce your exact problem. I put some code in there that prints out a message "Fixing up empty image to size" if your condition occurs, and then it falls back to using the image size, but I've never seen this actually happen.

I tested on OSX, Linux, and Windows, both in windowed mode and --fullscreen, and all seems to be more robust now. Look forward to your feedback.

**Comment by sum1els** [comment] 2018-02-24 04:37
wow .. that works very well now. I run PFD and ND on my local machine and EICAS on my Mac, no problems. I have a GTX1080Ti and it does knock the framerate a bit.

What would be nice, the option for network only ? Not to render inside x-plane (the little windows), but just send the textures over the network, would that be better on the framerate inside x-plane ?

Anyway, this is very cool and I can imagine a lot of guys are gonna be happy with this !!!

**Comment by waynepiekarski** [comment] 2018-02-24 04:39
What kind of frame rate hit are you experiencing?

You can close the windows, and then they will not impose any draw penalty at all. There is no way to save this to the config though.

**Comment by sum1els** [comment] 2018-02-24 04:43
about 50% hit, goes down to about 20fps from around 40 ... just tried closing all the windows inside x-plane and all my images in the java clients froze ?

**Comment by waynepiekarski** [comment] 2018-02-24 05:05
Ah yeah, you need at least one window open to keep the texture grab occuring. There is no way around this due to the way I intercept the textures.

However, does the frame rate drop happen when there are no network clients? The network transmission is done on a different thread, and if no clients are connected, it should not copy the texture either.

I'm running a GTX1080 and I notice only a small drop in frame rate, although I haven't tested it much.

**Comment by sum1els** [comment] 2018-02-24 05:50
Sitting at the gate, inside Zibo737 3d cockpit:

KATL, GATE A12, no plugin - 26fps
KATL, GATE A12, plugin, all windows - no clients connected - 26fps
KATL, GATE A12, plugin, all but one window - no clients - 26.5fps :)
KATL, GATE A12, plugin, all but one window - 1 client - 19fps
KATL, GATE A12, plugin, all but one window - 2 clients 18fps
 
Clients disconnected, back to 26fps

So it's not actually the rendering in x-plane itself, by the looks of it, but as soon as clients connect.

Anyway, it's not a big deal, just cool that we can now get the textures over the network at the sacrifice of a few fps, understandably.

**Comment by waynepiekarski** [comment] 2018-02-24 07:29
I need to sit down and actually test this out, I've spent more time writing the plugin than I have flying the plane :)

There are lots of tricks I can do to optimize the texture capturing, right now I grab the entire 2048x2048 but the Zibo only uses half of this. I need to experiment with grabbing smaller subsets and see if it helps at all. It might not if the slow down is caused by the OpenGL pipeline stalling. The rest of the steps are done on another thread so in theory should not impose much more overhead.

**Comment by waynepiekarski** [comment] 2018-03-07 06:24
So it turns out I can't grab smaller texture subsets, I may be stuck with the current 2048x2048 that I am grabbing. I've read about other tricks involving copying the texture to a PBO, but I don't know enough about how to do that.

I haven't had many complain about a 50% frame rate drop, in my case it is not really noticeable (20 -> 17 fps).

I also implemented borderless windows. You can now click the "H" button and it will make the UI go away, and you can click on the windows to bring them back to having frames. Give it a try!

**Comment by sum1els** [comment] 2018-03-07 12:46
thanks wayne. you know what i have noticed, when i click on any of the "buttons" in the windows, it does not do anything for me. pop-out, H, all those things, does nothing :) ...
anyway, i am going to try and redo some of the zibo graphics if i can, looks pretty low res when you resize the windows, would be interesting to see what affect that will have. thanks again !

**Comment by waynepiekarski** [comment] 2018-03-07 19:25
Clicking on the UI buttons like Ld, Sv, Pop-Out, etc, does not work for you? Has it ever worked in the past?

**Comment by sum1els** [comment] 2018-03-07 19:41
no never :) .. but it doesn't matter for me as i would use the java client anyway

**Comment by waynepiekarski** [comment] 2018-03-07 20:15
Are you running my pre-compiled plugin as-is, or are you rebuilding it for OSX or Linux or anything else different? I've never heard of the UI buttons not working from anyone.

**Comment by sum1els** [comment] 2018-03-07 21:58
pre-compiled, as is, on windows 10, just copies the plugin folder to my xplane.

**Comment by cenda737** [comment] 2018-03-18 08:46
DearWayne, thank you very much for this plug-in! It’s incredible! May I give you one suggestion for java client: it would be fantastic to have some kind of config file (or maybe just calling parameters) where to store/specify window startup position on client PC. I’m testing your plugin on Win10 and it works pretty well! Hats off! Petr

**Comment by waynepiekarski** [comment] 2018-03-19 19:27
@cenda737 unfortunately my Windows knowledge is quite limited, and not sure how to do this from within Java. There is --fullscreen which seems to work, but beyond that I don't know. My main plan was for the Java client to run on old laptops and Raspberry Pi 3 devices, all of which only have a single screen. If you are running this on the same machine as what is running X-Plane, you are probably better off letting XTE render the windows directly on the same GPU since the texture is already loaded.

If anyone knows how to do the window layouts in Java/Windows, I'd be happy to merge in a pull request though!

**Closed as completed** 2021-09-04 07:49 UTC
